/*
 * Natural Voice SDK
 * Natural Voice SDKs are easiest and best supported way for most developers to quickly build and iterate Natural Voice applications that integrate with our services programmatically.
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * NlpData
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-02-28T17:25:36.876-07:00")
public class NlpData {
  @SerializedName("audioId")
  private String audioId = null;

  @SerializedName("sentiment")
  private Object sentiment = null;

  @SerializedName("syntax")
  private Object syntax = null;

  @SerializedName("entities")
  private Object entities = null;

  public NlpData audioId(String audioId) {
    this.audioId = audioId;
    return this;
  }

   /**
   * Get audioId
   * @return audioId
  **/
  @ApiModelProperty(value = "")
  public String getAudioId() {
    return audioId;
  }

  public void setAudioId(String audioId) {
    this.audioId = audioId;
  }

  public NlpData sentiment(Object sentiment) {
    this.sentiment = sentiment;
    return this;
  }

   /**
   * https://godoc.org/google.golang.org/genproto/googleapis/cloud/language/v1#AnalyzeSentimentResponse
   * @return sentiment
  **/
  @ApiModelProperty(value = "https://godoc.org/google.golang.org/genproto/googleapis/cloud/language/v1#AnalyzeSentimentResponse")
  public Object getSentiment() {
    return sentiment;
  }

  public void setSentiment(Object sentiment) {
    this.sentiment = sentiment;
  }

  public NlpData syntax(Object syntax) {
    this.syntax = syntax;
    return this;
  }

   /**
   * https://godoc.org/google.golang.org/genproto/googleapis/cloud/language/v1#AnalyzeSyntaxResponse
   * @return syntax
  **/
  @ApiModelProperty(value = "https://godoc.org/google.golang.org/genproto/googleapis/cloud/language/v1#AnalyzeSyntaxResponse")
  public Object getSyntax() {
    return syntax;
  }

  public void setSyntax(Object syntax) {
    this.syntax = syntax;
  }

  public NlpData entities(Object entities) {
    this.entities = entities;
    return this;
  }

   /**
   * https://godoc.org/google.golang.org/genproto/googleapis/cloud/language/v1#AnalyzeEntitiesResponse
   * @return entities
  **/
  @ApiModelProperty(value = "https://godoc.org/google.golang.org/genproto/googleapis/cloud/language/v1#AnalyzeEntitiesResponse")
  public Object getEntities() {
    return entities;
  }

  public void setEntities(Object entities) {
    this.entities = entities;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NlpData nlpData = (NlpData) o;
    return Objects.equals(this.audioId, nlpData.audioId) &&
        Objects.equals(this.sentiment, nlpData.sentiment) &&
        Objects.equals(this.syntax, nlpData.syntax) &&
        Objects.equals(this.entities, nlpData.entities);
  }

  @Override
  public int hashCode() {
    return Objects.hash(audioId, sentiment, syntax, entities);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NlpData {\n");
    
    sb.append("    audioId: ").append(toIndentedString(audioId)).append("\n");
    sb.append("    sentiment: ").append(toIndentedString(sentiment)).append("\n");
    sb.append("    syntax: ").append(toIndentedString(syntax)).append("\n");
    sb.append("    entities: ").append(toIndentedString(entities)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

