/*
 * AimMatic API
 * APIs for Natural Voice and placeNext
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.ApiResponse;
import io.swagger.client.model.ESSResponse;
import org.junit.Assert;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ESSScoreApi
 */
public class ESSScoreApiTest extends BaseTest {

    private final ESSApi api = new ESSApi();

    /**
     * Retrieve ESS Score
     *
     * Retrieve ESS Score 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void insightsEssGetTest() throws ApiException {
        setup(api.getApiClient());
        Long start = null;
        Long end = null;
        Float saliencevalue = 0.9f;
        ApiResponse<ESSResponse> res = api.insightsEssGetWithHttpInfo(saliencevalue,start, end);
        Assert.assertEquals("status", 200, res.getStatusCode());
    }
    
}
