/*
 * AimMatic API
 * APIs for Natural Voice and placeNext
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.ApiResponse;
import io.swagger.client.model.NLPDocumentResponse;
import org.junit.Assert;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for NLPResultsApi
 */

public class NLPResultsApiTest extends BaseTest {

    private final NLPResultsApi api = new NLPResultsApi();

    /**
     * Query Natural Voice for text analysis results
     *
     * Developers use the NLPResults API to query Natural Voice to retrieve document sentiment, named entities, and syntax analysis after natural language processing (NLP). Optionally can provide a start and end date range to retrieve the results from a corpus of Natural Voice sessions. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void insightsNLPResultsGetTest() throws ApiException {
        setup(api.getApiClient());
        Long start = null;
        Long end = null;
        /*NLPDocumentResponse res = api.insightsNLPResultsGet(getAudioId(), start, end);

        Assert.assertEquals("status", 200, res.getCode().intValue());*/

        ApiResponse<NLPDocumentResponse> res = api.insightsNLPResultsGetWithHttpInfo(getAudioId(), start, end);
        Assert.assertEquals("status", 200, res.getStatusCode());
        NLPDocumentResponse body = res.getData();
    }
    
}
